### ISSUE TITLE
Can I use rapppid for to checking intraspecific PPI in plasmodium

### ISSUE THREAD

**Issue by Rohit-Satyam** [jszym/rapppid#4]
Hi @jszym 

I was wondering if I could use the pre-trained model checkpoint file to assess PPI in few plasmodium proteins that I want to check the interaction in or if the model is not generic?

**Comment by jszym** [comment]
Hello! Thanks for your interest in RAPPPID :)

While the RAPPPID weights here are indeed trained exclusively on Human proteins, RAPPPID's cross-species performance is shown to surpass leading methods in [our latest work](https://www.biorxiv.org/content/10.1101/2024.02.13.580150v1).

That work actually outlines [INTREPPPID](https://github.com/emad-combine-lab/intrepppid), a model we designed to specifically address the cross-species task. We find INTREPPPID to have superior performance to RAPPPID, especially in the cross-species case.

Note that if there is sufficient PPI data on your organism of interest, you are likely to get the best results training a RAPPPID model directly on that data.

Finally, the easiest way to use the existing human RAPPPID and INTREPPPID weights is via [ppi.bio](https://ppi.bio). It's in beta, so there may be some bugs, but generally speaking it's a very fast way to infer PPI using our algorithms.
